### PR TITLE
Fix for 2015

### PR DESCRIPTION
**Pull request by quinn56**

### CODE REVIEW

**Comment by scottopell** [comment]
This repository is effectively dead and only staying around for archival purposes.

Please check the current course repository for the latest version (lab4 is still being worked on)
https://github.com/Purdue-CSUSB/CSToolsCourse

**Comment by quinn56** [comment]
the magic script for lab 4 downloads this, just trying to give you a heads up.

**Comment by scottopell** [comment]
Awesome! thanks for the heads up!

**Comment by leviathan747** [comment]
Yo @quinn56 lab 4 is still being worked on. I will post the link to it on the syllabus, but until I do that consider it in an unfinished state. If you work on it ahead you are at risk of having to redo some work :/

**Pull request closed without merging**
